# Generated by Django 4.2.9 on 2024-11-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_kategoria_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='tranzakcje',
            name='jednorazowa',
            field=models.BooleanField(default=True),
        ),
    ]
