# Generated by Django 4.2.9 on 2024-11-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_tranzakcje_jednorazowa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tranzakcje',
            name='jednorazowa',
            field=models.BooleanField(),
        ),
    ]
